Milestone 2 -Interactive list
Jmagero/to-dos-list pull request #2
Opened 2021-07-15 22:09 UTC by Jmagero

2021-07-15 22:14 UTC, Jmagero commented
- [x] Add methods related to drag / drop and sorting functionality.
- [x] Add methods related to the status updates (completed: true / false).
- [x] Add event listeners to list items (dragstart, dragover, drop) and to checkbox (change).
- [x] Updated items object's values for index and completed keys upon user actions.
- [x] Add methods to store the updated array of items in local storage

2021-07-15 22:35 UTC, bellom commented
> * [x]  Add methods related to drag / drop and sorting functionality.
> * [x]  Add methods related to the status updates (completed: true / false).
> * [x]  Add event listeners to list items (dragstart, dragover, drop) and to checkbox (change).
> * [x]  Updated items object's values for index and completed keys upon user actions.
> * [x]  Add methods to store the updated array of items in local storage

Good job adding a PR description but you can always edit the first one with no PR description.

2021-07-15 23:10 UTC, bellom requested changes
## Hi @Jmagero  👏 , 

### Awesome job so far!! :+1: 

# Status: Required Changes! ♻️ 

1. Kindly check the comments under the review.
2. Kindly implement the drag feature and let's work a little on the UI to fit in with the requirement.


### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-15 23:10 UTC, bellom commented on dist/index.html
> +              <ul id="tasks" class="listClass d-flex w-50 flex-column" class = "drag-sort-enable"></ul>
Let's try to follow good [HTML/CSS practice](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md):
`class = "drag-sort-enable"` Use space-less equal signs, like this `class="drag-sort-enable"`

2021-07-16 12:51 UTC, Jmagero commented
- [x]  Implement the drag feature and let's work a little on the UI to fit in with the requirement

2021-07-16 13:48 UTC, ZawadiSumba66 approved these changes
#### Hi @Jmagero 👋 , 
Good job implementing the changes requested by the previous reviewer 💯 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-20 23:14 UTC, merged